### ISSUE TITLE
Handling of the different experiments in not streamlined

### ISSUE THREAD

**Issue by jstutters** [colournaming/colournaming#221]
Currently adding a new experiment with only slightly different parameters requires adding database tables and new submodules.  This should be more streamlined.

### Tasks

- [ ] Identify everything about the experiment we might want to alter (background, foreground etc.)
- [ ] Update the existing database models for response and participant to cope with this
- [ ] Either add a class to represent experiments or encode this in the URL
